cargo: fix metadata fetching by removing workspace table
*Because workspace.exclude doesn't support glob syntax.*

error: current package believes it's in a workspace when it's not:
current:   /rust/my/docs/repos/os-checker/plugin-cargo/Cargo.toml
workspace: /rust/my/docs/Cargo.toml

this may be fixable by ensuring that this crate is depended on by the workspace root: /rust/my/docs/Cargo.toml
Alternatively, to keep it out of the workspace, add the package to the `workspace.exclude` array, or add an empty `[workspace]` table to the package's manif
est.

ref: https://github.com/rust-lang/cargo/issues/6009